# SQL DataBase

In [8]:
import duckdb
import pandas as pd

# Loading CVS into DuckDB
See associate sql database file (database.sql) to get a better understanding of the tables

In [4]:
connection = duckdb.connect(database=':memory:')

connection.execute("""
CREATE TABLE housing_data AS
SELECT * FROM read_csv_auto('../data/MedianPricesofExistingDetachedHomesHistoricalData - Median Price.csv', header=True, skip=1)

""")

connection.execute("""
CREATE TABLE population AS
SELECT * FROM read_csv_auto('../data/population_clean.csv', header=True)
""")

connection.execute("""
CREATE TABLE debt AS
SELECT * FROM read_csv_auto('../data/debt_2003_2025 _clean.csv', header=True)
""")

# Query debt, housing, and population tables

In [5]:
# Querying debt data from 2003 to 2025

connection.execute("""
SELECT
    CAST('20' || SUBSTR(quarter, 1, 2) AS INT) AS year,
    quarter,
    Mortgage,
    "Credit Card"   AS credit_card,
    "Student Loan"  AS student_loan,
    "Auto Loan"     AS auto_loan,
    "HE Revolving"  AS he_revolving
FROM debt
WHERE CAST('20' || SUBSTR(quarter, 1, 2) AS INT) BETWEEN 2003 AND 2025;
""").fetchdf()


# avg debt by year

connection.execute("""
SELECT
    CAST('20' || SUBSTR(quarter, 1, 2) AS INT) AS year,
    AVG(Mortgage)       AS avg_mortgage,
    AVG("Credit Card")  AS avg_credit_card,
    AVG("Student Loan") AS avg_student_loan,
    AVG("Auto Loan")    AS avg_auto_loan,
    AVG("HE Revolving") AS avg_he_revolving
FROM debt
GROUP BY year
ORDER BY year;
""").fetchdf()

,year,avg_mortgage,avg_credit_card,avg_student_loan,avg_auto_loan,avg_he_revolving
0,2003,5.215000,0.69250,0.245000,0.660000,0.267500
1,2004,6.095000,0.70750,0.300000,0.735000,0.400000
2,2005,6.805000,0.72500,0.375000,0.780000,0.535000
3,2006,7.870000,0.74500,0.450000,0.807500,0.592500
4,2007,8.790000,0.80500,0.525000,0.810000,0.627500
5,2008,9.262500,0.85500,0.605000,0.805000,0.685000
6,2009,8.995000,0.81750,0.687500,0.742500,0.710000
7,2010,8.647500,0.74000,0.777500,0.705000,0.680000
8,2011,8.432500,0.69500,0.857500,0.720000,0.632500
9,2012,8.100000,0.67500,0.935000,0.760000,0.582500
10,2013,7.930000,0.67000,1.022500,0.827500,0.540000
11,2014,8.142500,0.67750,1.130000,0.920000,0.517500
12,2015,8.200000,0.70500,1.202500,1.022500,0.497500
13,2016,8.390000,0.74250,1.277500,1.117500,0.477500
14,2017,8.735000,0.79500,1.355000,1.197500,0.450000
15,2018,9.050000,0.84000,1.430000,1.252500,0.425000
16,2019,9.412500,0.88250,1.495000,1.307500,0.400000
17,2020,9.847500,0.83475,1.546250,1.356000,0.369000
18,2021,10.550000,0.80425,1.578500,1.424500,0.323000
19,2022,11.540000,0.90975,1.587000,1.511750,0.323500
20,2023,12.110000,1.05625,1.593250,1.586500,0.347000
21,2024,12.540000,1.15850,1.600250,1.635250,0.384750
22,2025,12.936667,1.20800,1.640667,1.650667,0.411667

In [ ]:
# querying housing data --> TODO Need to fix and work on further
# df = pd.read_csv('../data/MedianPricesofExistingDetachedHomesHistoricalData - Median Price.csv', header=1)
# df.columns = [c.strip().lower().replace(' ', '_') for c in df.columns]

# connection.register('housing_data_df', df)
# connection.execute("CREATE TABLE housing_clean AS SELECT * FROM housing_data_df")
# connection.execute("SELECT * FROM housing_clean").fetchdf()

# connection.execute("SELECT * FROM housing_data").fetchdf()

list(connection.execute("SELECT * FROM housing_data LIMIT 1").fetchdf().columns)

['column0']

In [ ]:
# Querying population data
connection.execute("""
SELECT * FROM population
WHERE year BETWEEN 2000 AND 2020
ORDER BY year;
""").fetchdf()

# population growth rate comparing each year to previous year
connection.execute("""
SELECT
                   year,
                   population,
                   LAG(population) OVER (ORDER BY year) AS previous_population,
                   ROUND(((population - LAG(population) OVER (ORDER BY year)) * 100.0) / LAG(population) OVER (ORDER BY year), 2) AS growth_rate_percentage
FROM population 
WHERE year BETWEEN 2000 AND 2020
ORDER BY year;
""").fetchdf()

    year  population  previous_population  growth_rate_percentage
0   2000   33987.977                  NaN                     NaN
1   2001   34479.458            33987.977                    1.45
2   2002   34871.843            34479.458                    1.14
3   2003   35253.159            34871.843                    1.09
4   2004   35574.576            35253.159                    0.91
5   2005   35827.943            35574.576                    0.71
6   2006   36021.202            35827.943                    0.54
7   2007   36250.311            36021.202                    0.64
8   2008   36604.337            36250.311                    0.98
9   2009   36961.229            36604.337                    0.97
10  2010   37319.550            36961.229                    0.97
11  2011   37636.311            37319.550                    0.85
12  2012   37944.551            37636.311                    0.82
13  2013   38253.768            37944.551                    0.81
14  2014   38586.706            38253.768                    0.87
15  2015   38904.296            38586.706                    0.82
16  2016   39149.186            38904.296                    0.63
17  2017   39337.785            39149.186                    0.48
18  2018   39437.463            39337.785                    0.25
19  2019   39437.610            39437.463                    0.00
20  2020   39521.958            39437.610                    0.21